/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: modules/ActionModule.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "modules/ActionModule.pb-c.h"
void   action_module__system_logger_status__init
                     (ActionModule__SystemLoggerStatus         *message)
{
  static const ActionModule__SystemLoggerStatus init_value = ACTION_MODULE__SYSTEM_LOGGER_STATUS__INIT;
  *message = init_value;
}
size_t action_module__system_logger_status__get_packed_size
                     (const ActionModule__SystemLoggerStatus *message)
{
  assert(message->base.descriptor == &action_module__system_logger_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__system_logger_status__pack
                     (const ActionModule__SystemLoggerStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__system_logger_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__system_logger_status__pack_to_buffer
                     (const ActionModule__SystemLoggerStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__system_logger_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__SystemLoggerStatus *
       action_module__system_logger_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__SystemLoggerStatus *)
     protobuf_c_message_unpack (&action_module__system_logger_status__descriptor,
                                allocator, len, data);
}
void   action_module__system_logger_status__free_unpacked
                     (ActionModule__SystemLoggerStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__system_logger_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__green_button_status__init
                     (ActionModule__GreenButtonStatus         *message)
{
  static const ActionModule__GreenButtonStatus init_value = ACTION_MODULE__GREEN_BUTTON_STATUS__INIT;
  *message = init_value;
}
size_t action_module__green_button_status__get_packed_size
                     (const ActionModule__GreenButtonStatus *message)
{
  assert(message->base.descriptor == &action_module__green_button_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__green_button_status__pack
                     (const ActionModule__GreenButtonStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__green_button_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__green_button_status__pack_to_buffer
                     (const ActionModule__GreenButtonStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__green_button_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__GreenButtonStatus *
       action_module__green_button_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__GreenButtonStatus *)
     protobuf_c_message_unpack (&action_module__green_button_status__descriptor,
                                allocator, len, data);
}
void   action_module__green_button_status__free_unpacked
                     (ActionModule__GreenButtonStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__green_button_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__red_button_status__init
                     (ActionModule__RedButtonStatus         *message)
{
  static const ActionModule__RedButtonStatus init_value = ACTION_MODULE__RED_BUTTON_STATUS__INIT;
  *message = init_value;
}
size_t action_module__red_button_status__get_packed_size
                     (const ActionModule__RedButtonStatus *message)
{
  assert(message->base.descriptor == &action_module__red_button_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__red_button_status__pack
                     (const ActionModule__RedButtonStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__red_button_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__red_button_status__pack_to_buffer
                     (const ActionModule__RedButtonStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__red_button_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__RedButtonStatus *
       action_module__red_button_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__RedButtonStatus *)
     protobuf_c_message_unpack (&action_module__red_button_status__descriptor,
                                allocator, len, data);
}
void   action_module__red_button_status__free_unpacked
                     (ActionModule__RedButtonStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__red_button_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__watchdog_status__init
                     (ActionModule__WatchdogStatus         *message)
{
  static const ActionModule__WatchdogStatus init_value = ACTION_MODULE__WATCHDOG_STATUS__INIT;
  *message = init_value;
}
size_t action_module__watchdog_status__get_packed_size
                     (const ActionModule__WatchdogStatus *message)
{
  assert(message->base.descriptor == &action_module__watchdog_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__watchdog_status__pack
                     (const ActionModule__WatchdogStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__watchdog_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__watchdog_status__pack_to_buffer
                     (const ActionModule__WatchdogStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__watchdog_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__WatchdogStatus *
       action_module__watchdog_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__WatchdogStatus *)
     protobuf_c_message_unpack (&action_module__watchdog_status__descriptor,
                                allocator, len, data);
}
void   action_module__watchdog_status__free_unpacked
                     (ActionModule__WatchdogStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__watchdog_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__system_logger_command__init
                     (ActionModule__SystemLoggerCommand         *message)
{
  static const ActionModule__SystemLoggerCommand init_value = ACTION_MODULE__SYSTEM_LOGGER_COMMAND__INIT;
  *message = init_value;
}
size_t action_module__system_logger_command__get_packed_size
                     (const ActionModule__SystemLoggerCommand *message)
{
  assert(message->base.descriptor == &action_module__system_logger_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__system_logger_command__pack
                     (const ActionModule__SystemLoggerCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__system_logger_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__system_logger_command__pack_to_buffer
                     (const ActionModule__SystemLoggerCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__system_logger_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__SystemLoggerCommand *
       action_module__system_logger_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__SystemLoggerCommand *)
     protobuf_c_message_unpack (&action_module__system_logger_command__descriptor,
                                allocator, len, data);
}
void   action_module__system_logger_command__free_unpacked
                     (ActionModule__SystemLoggerCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__system_logger_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__green_button_command__init
                     (ActionModule__GreenButtonCommand         *message)
{
  static const ActionModule__GreenButtonCommand init_value = ACTION_MODULE__GREEN_BUTTON_COMMAND__INIT;
  *message = init_value;
}
size_t action_module__green_button_command__get_packed_size
                     (const ActionModule__GreenButtonCommand *message)
{
  assert(message->base.descriptor == &action_module__green_button_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__green_button_command__pack
                     (const ActionModule__GreenButtonCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__green_button_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__green_button_command__pack_to_buffer
                     (const ActionModule__GreenButtonCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__green_button_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__GreenButtonCommand *
       action_module__green_button_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__GreenButtonCommand *)
     protobuf_c_message_unpack (&action_module__green_button_command__descriptor,
                                allocator, len, data);
}
void   action_module__green_button_command__free_unpacked
                     (ActionModule__GreenButtonCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__green_button_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__red_button_command__init
                     (ActionModule__RedButtonCommand         *message)
{
  static const ActionModule__RedButtonCommand init_value = ACTION_MODULE__RED_BUTTON_COMMAND__INIT;
  *message = init_value;
}
size_t action_module__red_button_command__get_packed_size
                     (const ActionModule__RedButtonCommand *message)
{
  assert(message->base.descriptor == &action_module__red_button_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__red_button_command__pack
                     (const ActionModule__RedButtonCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__red_button_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__red_button_command__pack_to_buffer
                     (const ActionModule__RedButtonCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__red_button_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__RedButtonCommand *
       action_module__red_button_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__RedButtonCommand *)
     protobuf_c_message_unpack (&action_module__red_button_command__descriptor,
                                allocator, len, data);
}
void   action_module__red_button_command__free_unpacked
                     (ActionModule__RedButtonCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__red_button_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__watchdog_command__init
                     (ActionModule__WatchdogCommand         *message)
{
  static const ActionModule__WatchdogCommand init_value = ACTION_MODULE__WATCHDOG_COMMAND__INIT;
  *message = init_value;
}
size_t action_module__watchdog_command__get_packed_size
                     (const ActionModule__WatchdogCommand *message)
{
  assert(message->base.descriptor == &action_module__watchdog_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__watchdog_command__pack
                     (const ActionModule__WatchdogCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__watchdog_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__watchdog_command__pack_to_buffer
                     (const ActionModule__WatchdogCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__watchdog_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__WatchdogCommand *
       action_module__watchdog_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__WatchdogCommand *)
     protobuf_c_message_unpack (&action_module__watchdog_command__descriptor,
                                allocator, len, data);
}
void   action_module__watchdog_command__free_unpacked
                     (ActionModule__WatchdogCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__watchdog_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__system_logger_error__init
                     (ActionModule__SystemLoggerError         *message)
{
  static const ActionModule__SystemLoggerError init_value = ACTION_MODULE__SYSTEM_LOGGER_ERROR__INIT;
  *message = init_value;
}
size_t action_module__system_logger_error__get_packed_size
                     (const ActionModule__SystemLoggerError *message)
{
  assert(message->base.descriptor == &action_module__system_logger_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__system_logger_error__pack
                     (const ActionModule__SystemLoggerError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__system_logger_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__system_logger_error__pack_to_buffer
                     (const ActionModule__SystemLoggerError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__system_logger_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__SystemLoggerError *
       action_module__system_logger_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__SystemLoggerError *)
     protobuf_c_message_unpack (&action_module__system_logger_error__descriptor,
                                allocator, len, data);
}
void   action_module__system_logger_error__free_unpacked
                     (ActionModule__SystemLoggerError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__system_logger_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__green_button_error__init
                     (ActionModule__GreenButtonError         *message)
{
  static const ActionModule__GreenButtonError init_value = ACTION_MODULE__GREEN_BUTTON_ERROR__INIT;
  *message = init_value;
}
size_t action_module__green_button_error__get_packed_size
                     (const ActionModule__GreenButtonError *message)
{
  assert(message->base.descriptor == &action_module__green_button_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__green_button_error__pack
                     (const ActionModule__GreenButtonError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__green_button_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__green_button_error__pack_to_buffer
                     (const ActionModule__GreenButtonError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__green_button_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__GreenButtonError *
       action_module__green_button_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__GreenButtonError *)
     protobuf_c_message_unpack (&action_module__green_button_error__descriptor,
                                allocator, len, data);
}
void   action_module__green_button_error__free_unpacked
                     (ActionModule__GreenButtonError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__green_button_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__red_button_error__init
                     (ActionModule__RedButtonError         *message)
{
  static const ActionModule__RedButtonError init_value = ACTION_MODULE__RED_BUTTON_ERROR__INIT;
  *message = init_value;
}
size_t action_module__red_button_error__get_packed_size
                     (const ActionModule__RedButtonError *message)
{
  assert(message->base.descriptor == &action_module__red_button_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__red_button_error__pack
                     (const ActionModule__RedButtonError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__red_button_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__red_button_error__pack_to_buffer
                     (const ActionModule__RedButtonError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__red_button_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__RedButtonError *
       action_module__red_button_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__RedButtonError *)
     protobuf_c_message_unpack (&action_module__red_button_error__descriptor,
                                allocator, len, data);
}
void   action_module__red_button_error__free_unpacked
                     (ActionModule__RedButtonError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__red_button_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   action_module__watchdog_error__init
                     (ActionModule__WatchdogError         *message)
{
  static const ActionModule__WatchdogError init_value = ACTION_MODULE__WATCHDOG_ERROR__INIT;
  *message = init_value;
}
size_t action_module__watchdog_error__get_packed_size
                     (const ActionModule__WatchdogError *message)
{
  assert(message->base.descriptor == &action_module__watchdog_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t action_module__watchdog_error__pack
                     (const ActionModule__WatchdogError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &action_module__watchdog_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t action_module__watchdog_error__pack_to_buffer
                     (const ActionModule__WatchdogError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &action_module__watchdog_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ActionModule__WatchdogError *
       action_module__watchdog_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ActionModule__WatchdogError *)
     protobuf_c_message_unpack (&action_module__watchdog_error__descriptor,
                                allocator, len, data);
}
void   action_module__watchdog_error__free_unpacked
                     (ActionModule__WatchdogError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &action_module__watchdog_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue action_module__system_logger_status__verbosity__enum_values_by_number[4] =
{
  { "DEBUG", "ACTION_MODULE__SYSTEM_LOGGER_STATUS__VERBOSITY__DEBUG", 0 },
  { "INFO", "ACTION_MODULE__SYSTEM_LOGGER_STATUS__VERBOSITY__INFO", 5 },
  { "WARNING", "ACTION_MODULE__SYSTEM_LOGGER_STATUS__VERBOSITY__WARNING", 10 },
  { "ERROR", "ACTION_MODULE__SYSTEM_LOGGER_STATUS__VERBOSITY__ERROR", 15 },
};
static const ProtobufCIntRange action_module__system_logger_status__verbosity__value_ranges[] = {
{0, 0},{5, 1},{10, 2},{15, 3},{0, 4}
};
static const ProtobufCEnumValueIndex action_module__system_logger_status__verbosity__enum_values_by_name[4] =
{
  { "DEBUG", 0 },
  { "ERROR", 3 },
  { "INFO", 1 },
  { "WARNING", 2 },
};
const ProtobufCEnumDescriptor action_module__system_logger_status__verbosity__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ActionModule.SystemLoggerStatus.Verbosity",
  "Verbosity",
  "ActionModule__SystemLoggerStatus__Verbosity",
  "ActionModule",
  4,
  action_module__system_logger_status__verbosity__enum_values_by_number,
  4,
  action_module__system_logger_status__verbosity__enum_values_by_name,
  4,
  action_module__system_logger_status__verbosity__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor action_module__system_logger_status__field_descriptors[3] =
{
  {
    "sourceDevice",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionModule__SystemLoggerStatus, sourcedevice),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ActionModule__SystemLoggerStatus, n_logs),
    offsetof(ActionModule__SystemLoggerStatus, logs),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "verbosity",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ActionModule__SystemLoggerStatus, verbosity),
    &action_module__system_logger_status__verbosity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__system_logger_status__field_indices_by_name[] = {
  1,   /* field[1] = logs */
  0,   /* field[0] = sourceDevice */
  2,   /* field[2] = verbosity */
};
static const ProtobufCIntRange action_module__system_logger_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor action_module__system_logger_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.SystemLoggerStatus",
  "SystemLoggerStatus",
  "ActionModule__SystemLoggerStatus",
  "ActionModule",
  sizeof(ActionModule__SystemLoggerStatus),
  3,
  action_module__system_logger_status__field_descriptors,
  action_module__system_logger_status__field_indices_by_name,
  1,  action_module__system_logger_status__number_ranges,
  (ProtobufCMessageInit) action_module__system_logger_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_module__green_button_status__field_descriptors[2] =
{
  {
    "isPressed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ActionModule__GreenButtonStatus, ispressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isAlive",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ActionModule__GreenButtonStatus, isalive),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__green_button_status__field_indices_by_name[] = {
  1,   /* field[1] = isAlive */
  0,   /* field[0] = isPressed */
};
static const ProtobufCIntRange action_module__green_button_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_module__green_button_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.GreenButtonStatus",
  "GreenButtonStatus",
  "ActionModule__GreenButtonStatus",
  "ActionModule",
  sizeof(ActionModule__GreenButtonStatus),
  2,
  action_module__green_button_status__field_descriptors,
  action_module__green_button_status__field_indices_by_name,
  1,  action_module__green_button_status__number_ranges,
  (ProtobufCMessageInit) action_module__green_button_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_module__red_button_status__field_descriptors[1] =
{
  {
    "isPressed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ActionModule__RedButtonStatus, ispressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__red_button_status__field_indices_by_name[] = {
  0,   /* field[0] = isPressed */
};
static const ProtobufCIntRange action_module__red_button_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__red_button_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.RedButtonStatus",
  "RedButtonStatus",
  "ActionModule__RedButtonStatus",
  "ActionModule",
  sizeof(ActionModule__RedButtonStatus),
  1,
  action_module__red_button_status__field_descriptors,
  action_module__red_button_status__field_indices_by_name,
  1,  action_module__red_button_status__number_ranges,
  (ProtobufCMessageInit) action_module__red_button_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_module__watchdog_status__field_descriptors[2] =
{
  {
    "isAlive",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ActionModule__WatchdogStatus, isalive),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionModule__WatchdogStatus, state),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__watchdog_status__field_indices_by_name[] = {
  0,   /* field[0] = isAlive */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange action_module__watchdog_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor action_module__watchdog_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.WatchdogStatus",
  "WatchdogStatus",
  "ActionModule__WatchdogStatus",
  "ActionModule",
  sizeof(ActionModule__WatchdogStatus),
  2,
  action_module__watchdog_status__field_descriptors,
  action_module__watchdog_status__field_indices_by_name,
  1,  action_module__watchdog_status__number_ranges,
  (ProtobufCMessageInit) action_module__watchdog_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue action_module__system_logger_command__command__enum_values_by_number[1] =
{
  { "LOG", "ACTION_MODULE__SYSTEM_LOGGER_COMMAND__COMMAND__LOG", 0 },
};
static const ProtobufCIntRange action_module__system_logger_command__command__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex action_module__system_logger_command__command__enum_values_by_name[1] =
{
  { "LOG", 0 },
};
const ProtobufCEnumDescriptor action_module__system_logger_command__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ActionModule.SystemLoggerCommand.Command",
  "Command",
  "ActionModule__SystemLoggerCommand__Command",
  "ActionModule",
  1,
  action_module__system_logger_command__command__enum_values_by_number,
  1,
  action_module__system_logger_command__command__enum_values_by_name,
  1,
  action_module__system_logger_command__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor action_module__system_logger_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ActionModule__SystemLoggerCommand, command),
    &action_module__system_logger_command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__system_logger_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange action_module__system_logger_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__system_logger_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.SystemLoggerCommand",
  "SystemLoggerCommand",
  "ActionModule__SystemLoggerCommand",
  "ActionModule",
  sizeof(ActionModule__SystemLoggerCommand),
  1,
  action_module__system_logger_command__field_descriptors,
  action_module__system_logger_command__field_indices_by_name,
  1,  action_module__system_logger_command__number_ranges,
  (ProtobufCMessageInit) action_module__system_logger_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue action_module__green_button_command__command__enum_values_by_number[1] =
{
  { "PRESS", "ACTION_MODULE__GREEN_BUTTON_COMMAND__COMMAND__PRESS", 0 },
};
static const ProtobufCIntRange action_module__green_button_command__command__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex action_module__green_button_command__command__enum_values_by_name[1] =
{
  { "PRESS", 0 },
};
const ProtobufCEnumDescriptor action_module__green_button_command__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ActionModule.GreenButtonCommand.Command",
  "Command",
  "ActionModule__GreenButtonCommand__Command",
  "ActionModule",
  1,
  action_module__green_button_command__command__enum_values_by_number,
  1,
  action_module__green_button_command__command__enum_values_by_name,
  1,
  action_module__green_button_command__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor action_module__green_button_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ActionModule__GreenButtonCommand, command),
    &action_module__green_button_command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__green_button_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange action_module__green_button_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__green_button_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.GreenButtonCommand",
  "GreenButtonCommand",
  "ActionModule__GreenButtonCommand",
  "ActionModule",
  sizeof(ActionModule__GreenButtonCommand),
  1,
  action_module__green_button_command__field_descriptors,
  action_module__green_button_command__field_indices_by_name,
  1,  action_module__green_button_command__number_ranges,
  (ProtobufCMessageInit) action_module__green_button_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue action_module__red_button_command__command__enum_values_by_number[1] =
{
  { "PRESS", "ACTION_MODULE__RED_BUTTON_COMMAND__COMMAND__PRESS", 0 },
};
static const ProtobufCIntRange action_module__red_button_command__command__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex action_module__red_button_command__command__enum_values_by_name[1] =
{
  { "PRESS", 0 },
};
const ProtobufCEnumDescriptor action_module__red_button_command__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ActionModule.RedButtonCommand.Command",
  "Command",
  "ActionModule__RedButtonCommand__Command",
  "ActionModule",
  1,
  action_module__red_button_command__command__enum_values_by_number,
  1,
  action_module__red_button_command__command__enum_values_by_name,
  1,
  action_module__red_button_command__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor action_module__red_button_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ActionModule__RedButtonCommand, command),
    &action_module__red_button_command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__red_button_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange action_module__red_button_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__red_button_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.RedButtonCommand",
  "RedButtonCommand",
  "ActionModule__RedButtonCommand",
  "ActionModule",
  sizeof(ActionModule__RedButtonCommand),
  1,
  action_module__red_button_command__field_descriptors,
  action_module__red_button_command__field_indices_by_name,
  1,  action_module__red_button_command__number_ranges,
  (ProtobufCMessageInit) action_module__red_button_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue action_module__watchdog_command__command__enum_values_by_number[1] =
{
  { "RESET", "ACTION_MODULE__WATCHDOG_COMMAND__COMMAND__RESET", 0 },
};
static const ProtobufCIntRange action_module__watchdog_command__command__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex action_module__watchdog_command__command__enum_values_by_name[1] =
{
  { "RESET", 0 },
};
const ProtobufCEnumDescriptor action_module__watchdog_command__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ActionModule.WatchdogCommand.Command",
  "Command",
  "ActionModule__WatchdogCommand__Command",
  "ActionModule",
  1,
  action_module__watchdog_command__command__enum_values_by_number,
  1,
  action_module__watchdog_command__command__enum_values_by_name,
  1,
  action_module__watchdog_command__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor action_module__watchdog_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ActionModule__WatchdogCommand, command),
    &action_module__watchdog_command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__watchdog_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange action_module__watchdog_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__watchdog_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.WatchdogCommand",
  "WatchdogCommand",
  "ActionModule__WatchdogCommand",
  "ActionModule",
  sizeof(ActionModule__WatchdogCommand),
  1,
  action_module__watchdog_command__field_descriptors,
  action_module__watchdog_command__field_indices_by_name,
  1,  action_module__watchdog_command__number_ranges,
  (ProtobufCMessageInit) action_module__watchdog_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_module__system_logger_error__field_descriptors[1] =
{
  {
    "errorMessage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionModule__SystemLoggerError, errormessage),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__system_logger_error__field_indices_by_name[] = {
  0,   /* field[0] = errorMessage */
};
static const ProtobufCIntRange action_module__system_logger_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__system_logger_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.SystemLoggerError",
  "SystemLoggerError",
  "ActionModule__SystemLoggerError",
  "ActionModule",
  sizeof(ActionModule__SystemLoggerError),
  1,
  action_module__system_logger_error__field_descriptors,
  action_module__system_logger_error__field_indices_by_name,
  1,  action_module__system_logger_error__number_ranges,
  (ProtobufCMessageInit) action_module__system_logger_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_module__green_button_error__field_descriptors[1] =
{
  {
    "errorMessage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionModule__GreenButtonError, errormessage),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__green_button_error__field_indices_by_name[] = {
  0,   /* field[0] = errorMessage */
};
static const ProtobufCIntRange action_module__green_button_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__green_button_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.GreenButtonError",
  "GreenButtonError",
  "ActionModule__GreenButtonError",
  "ActionModule",
  sizeof(ActionModule__GreenButtonError),
  1,
  action_module__green_button_error__field_descriptors,
  action_module__green_button_error__field_indices_by_name,
  1,  action_module__green_button_error__number_ranges,
  (ProtobufCMessageInit) action_module__green_button_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_module__red_button_error__field_descriptors[1] =
{
  {
    "errorMessage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionModule__RedButtonError, errormessage),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__red_button_error__field_indices_by_name[] = {
  0,   /* field[0] = errorMessage */
};
static const ProtobufCIntRange action_module__red_button_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__red_button_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.RedButtonError",
  "RedButtonError",
  "ActionModule__RedButtonError",
  "ActionModule",
  sizeof(ActionModule__RedButtonError),
  1,
  action_module__red_button_error__field_descriptors,
  action_module__red_button_error__field_indices_by_name,
  1,  action_module__red_button_error__number_ranges,
  (ProtobufCMessageInit) action_module__red_button_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor action_module__watchdog_error__field_descriptors[1] =
{
  {
    "errorMessage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ActionModule__WatchdogError, errormessage),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned action_module__watchdog_error__field_indices_by_name[] = {
  0,   /* field[0] = errorMessage */
};
static const ProtobufCIntRange action_module__watchdog_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor action_module__watchdog_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ActionModule.WatchdogError",
  "WatchdogError",
  "ActionModule__WatchdogError",
  "ActionModule",
  sizeof(ActionModule__WatchdogError),
  1,
  action_module__watchdog_error__field_descriptors,
  action_module__watchdog_error__field_indices_by_name,
  1,  action_module__watchdog_error__number_ranges,
  (ProtobufCMessageInit) action_module__watchdog_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
