/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: modules/CarAccessoryModule.proto */

#ifndef PROTOBUF_C_modules_2fCarAccessoryModule_2eproto__INCLUDED
#define PROTOBUF_C_modules_2fCarAccessoryModule_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct CarAccessoryModule__ButtonStatus CarAccessoryModule__ButtonStatus;
typedef struct CarAccessoryModule__ButtonCommand CarAccessoryModule__ButtonCommand;
typedef struct CarAccessoryModule__ButtonError CarAccessoryModule__ButtonError;


/* --- enums --- */

typedef enum _CarAccessoryModule__ButtonCommand__Command {
  CAR_ACCESSORY_MODULE__BUTTON_COMMAND__COMMAND__PRESS = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_ACCESSORY_MODULE__BUTTON_COMMAND__COMMAND)
} CarAccessoryModule__ButtonCommand__Command;

/* --- messages --- */

struct  CarAccessoryModule__ButtonStatus
{
  ProtobufCMessage base;
  protobuf_c_boolean ispressed;
};
#define CAR_ACCESSORY_MODULE__BUTTON_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_accessory_module__button_status__descriptor) \
    , 0 }


struct  CarAccessoryModule__ButtonCommand
{
  ProtobufCMessage base;
  CarAccessoryModule__ButtonCommand__Command command;
};
#define CAR_ACCESSORY_MODULE__BUTTON_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_accessory_module__button_command__descriptor) \
    , CAR_ACCESSORY_MODULE__BUTTON_COMMAND__COMMAND__PRESS }


struct  CarAccessoryModule__ButtonError
{
  ProtobufCMessage base;
  uint32_t presscount;
};
#define CAR_ACCESSORY_MODULE__BUTTON_ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_accessory_module__button_error__descriptor) \
    , 0 }


/* CarAccessoryModule__ButtonStatus methods */
void   car_accessory_module__button_status__init
                     (CarAccessoryModule__ButtonStatus         *message);
size_t car_accessory_module__button_status__get_packed_size
                     (const CarAccessoryModule__ButtonStatus   *message);
size_t car_accessory_module__button_status__pack
                     (const CarAccessoryModule__ButtonStatus   *message,
                      uint8_t             *out);
size_t car_accessory_module__button_status__pack_to_buffer
                     (const CarAccessoryModule__ButtonStatus   *message,
                      ProtobufCBuffer     *buffer);
CarAccessoryModule__ButtonStatus *
       car_accessory_module__button_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_accessory_module__button_status__free_unpacked
                     (CarAccessoryModule__ButtonStatus *message,
                      ProtobufCAllocator *allocator);
/* CarAccessoryModule__ButtonCommand methods */
void   car_accessory_module__button_command__init
                     (CarAccessoryModule__ButtonCommand         *message);
size_t car_accessory_module__button_command__get_packed_size
                     (const CarAccessoryModule__ButtonCommand   *message);
size_t car_accessory_module__button_command__pack
                     (const CarAccessoryModule__ButtonCommand   *message,
                      uint8_t             *out);
size_t car_accessory_module__button_command__pack_to_buffer
                     (const CarAccessoryModule__ButtonCommand   *message,
                      ProtobufCBuffer     *buffer);
CarAccessoryModule__ButtonCommand *
       car_accessory_module__button_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_accessory_module__button_command__free_unpacked
                     (CarAccessoryModule__ButtonCommand *message,
                      ProtobufCAllocator *allocator);
/* CarAccessoryModule__ButtonError methods */
void   car_accessory_module__button_error__init
                     (CarAccessoryModule__ButtonError         *message);
size_t car_accessory_module__button_error__get_packed_size
                     (const CarAccessoryModule__ButtonError   *message);
size_t car_accessory_module__button_error__pack
                     (const CarAccessoryModule__ButtonError   *message,
                      uint8_t             *out);
size_t car_accessory_module__button_error__pack_to_buffer
                     (const CarAccessoryModule__ButtonError   *message,
                      ProtobufCBuffer     *buffer);
CarAccessoryModule__ButtonError *
       car_accessory_module__button_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_accessory_module__button_error__free_unpacked
                     (CarAccessoryModule__ButtonError *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CarAccessoryModule__ButtonStatus_Closure)
                 (const CarAccessoryModule__ButtonStatus *message,
                  void *closure_data);
typedef void (*CarAccessoryModule__ButtonCommand_Closure)
                 (const CarAccessoryModule__ButtonCommand *message,
                  void *closure_data);
typedef void (*CarAccessoryModule__ButtonError_Closure)
                 (const CarAccessoryModule__ButtonError *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor car_accessory_module__button_status__descriptor;
extern const ProtobufCMessageDescriptor car_accessory_module__button_command__descriptor;
extern const ProtobufCEnumDescriptor    car_accessory_module__button_command__command__descriptor;
extern const ProtobufCMessageDescriptor car_accessory_module__button_error__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_modules_2fCarAccessoryModule_2eproto__INCLUDED */
