/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: modules/CarAccessoryModule.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "modules/CarAccessoryModule.pb-c.h"
void   car_accessory_module__button_status__init
                     (CarAccessoryModule__ButtonStatus         *message)
{
  static const CarAccessoryModule__ButtonStatus init_value = CAR_ACCESSORY_MODULE__BUTTON_STATUS__INIT;
  *message = init_value;
}
size_t car_accessory_module__button_status__get_packed_size
                     (const CarAccessoryModule__ButtonStatus *message)
{
  assert(message->base.descriptor == &car_accessory_module__button_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t car_accessory_module__button_status__pack
                     (const CarAccessoryModule__ButtonStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &car_accessory_module__button_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t car_accessory_module__button_status__pack_to_buffer
                     (const CarAccessoryModule__ButtonStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &car_accessory_module__button_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CarAccessoryModule__ButtonStatus *
       car_accessory_module__button_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CarAccessoryModule__ButtonStatus *)
     protobuf_c_message_unpack (&car_accessory_module__button_status__descriptor,
                                allocator, len, data);
}
void   car_accessory_module__button_status__free_unpacked
                     (CarAccessoryModule__ButtonStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &car_accessory_module__button_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   car_accessory_module__button_command__init
                     (CarAccessoryModule__ButtonCommand         *message)
{
  static const CarAccessoryModule__ButtonCommand init_value = CAR_ACCESSORY_MODULE__BUTTON_COMMAND__INIT;
  *message = init_value;
}
size_t car_accessory_module__button_command__get_packed_size
                     (const CarAccessoryModule__ButtonCommand *message)
{
  assert(message->base.descriptor == &car_accessory_module__button_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t car_accessory_module__button_command__pack
                     (const CarAccessoryModule__ButtonCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &car_accessory_module__button_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t car_accessory_module__button_command__pack_to_buffer
                     (const CarAccessoryModule__ButtonCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &car_accessory_module__button_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CarAccessoryModule__ButtonCommand *
       car_accessory_module__button_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CarAccessoryModule__ButtonCommand *)
     protobuf_c_message_unpack (&car_accessory_module__button_command__descriptor,
                                allocator, len, data);
}
void   car_accessory_module__button_command__free_unpacked
                     (CarAccessoryModule__ButtonCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &car_accessory_module__button_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   car_accessory_module__button_error__init
                     (CarAccessoryModule__ButtonError         *message)
{
  static const CarAccessoryModule__ButtonError init_value = CAR_ACCESSORY_MODULE__BUTTON_ERROR__INIT;
  *message = init_value;
}
size_t car_accessory_module__button_error__get_packed_size
                     (const CarAccessoryModule__ButtonError *message)
{
  assert(message->base.descriptor == &car_accessory_module__button_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t car_accessory_module__button_error__pack
                     (const CarAccessoryModule__ButtonError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &car_accessory_module__button_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t car_accessory_module__button_error__pack_to_buffer
                     (const CarAccessoryModule__ButtonError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &car_accessory_module__button_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CarAccessoryModule__ButtonError *
       car_accessory_module__button_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CarAccessoryModule__ButtonError *)
     protobuf_c_message_unpack (&car_accessory_module__button_error__descriptor,
                                allocator, len, data);
}
void   car_accessory_module__button_error__free_unpacked
                     (CarAccessoryModule__ButtonError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &car_accessory_module__button_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor car_accessory_module__button_status__field_descriptors[1] =
{
  {
    "isPressed",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(CarAccessoryModule__ButtonStatus, ispressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned car_accessory_module__button_status__field_indices_by_name[] = {
  0,   /* field[0] = isPressed */
};
static const ProtobufCIntRange car_accessory_module__button_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor car_accessory_module__button_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CarAccessoryModule.ButtonStatus",
  "ButtonStatus",
  "CarAccessoryModule__ButtonStatus",
  "CarAccessoryModule",
  sizeof(CarAccessoryModule__ButtonStatus),
  1,
  car_accessory_module__button_status__field_descriptors,
  car_accessory_module__button_status__field_indices_by_name,
  1,  car_accessory_module__button_status__number_ranges,
  (ProtobufCMessageInit) car_accessory_module__button_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue car_accessory_module__button_command__command__enum_values_by_number[1] =
{
  { "PRESS", "CAR_ACCESSORY_MODULE__BUTTON_COMMAND__COMMAND__PRESS", 0 },
};
static const ProtobufCIntRange car_accessory_module__button_command__command__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex car_accessory_module__button_command__command__enum_values_by_name[1] =
{
  { "PRESS", 0 },
};
const ProtobufCEnumDescriptor car_accessory_module__button_command__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CarAccessoryModule.ButtonCommand.Command",
  "Command",
  "CarAccessoryModule__ButtonCommand__Command",
  "CarAccessoryModule",
  1,
  car_accessory_module__button_command__command__enum_values_by_number,
  1,
  car_accessory_module__button_command__command__enum_values_by_name,
  1,
  car_accessory_module__button_command__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor car_accessory_module__button_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CarAccessoryModule__ButtonCommand, command),
    &car_accessory_module__button_command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned car_accessory_module__button_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange car_accessory_module__button_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor car_accessory_module__button_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CarAccessoryModule.ButtonCommand",
  "ButtonCommand",
  "CarAccessoryModule__ButtonCommand",
  "CarAccessoryModule",
  sizeof(CarAccessoryModule__ButtonCommand),
  1,
  car_accessory_module__button_command__field_descriptors,
  car_accessory_module__button_command__field_indices_by_name,
  1,  car_accessory_module__button_command__number_ranges,
  (ProtobufCMessageInit) car_accessory_module__button_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor car_accessory_module__button_error__field_descriptors[1] =
{
  {
    "pressCount",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CarAccessoryModule__ButtonError, presscount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned car_accessory_module__button_error__field_indices_by_name[] = {
  0,   /* field[0] = pressCount */
};
static const ProtobufCIntRange car_accessory_module__button_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor car_accessory_module__button_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CarAccessoryModule.ButtonError",
  "ButtonError",
  "CarAccessoryModule__ButtonError",
  "CarAccessoryModule",
  sizeof(CarAccessoryModule__ButtonError),
  1,
  car_accessory_module__button_error__field_descriptors,
  car_accessory_module__button_error__field_indices_by_name,
  1,  car_accessory_module__button_error__number_ranges,
  (ProtobufCMessageInit) car_accessory_module__button_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
