/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: modules/ExampleModule.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "modules/ExampleModule.pb-c.h"
void   example_module__blinker_status__init
                     (ExampleModule__BlinkerStatus         *message)
{
  static const ExampleModule__BlinkerStatus init_value = EXAMPLE_MODULE__BLINKER_STATUS__INIT;
  *message = init_value;
}
size_t example_module__blinker_status__get_packed_size
                     (const ExampleModule__BlinkerStatus *message)
{
  assert(message->base.descriptor == &example_module__blinker_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t example_module__blinker_status__pack
                     (const ExampleModule__BlinkerStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &example_module__blinker_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t example_module__blinker_status__pack_to_buffer
                     (const ExampleModule__BlinkerStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &example_module__blinker_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExampleModule__BlinkerStatus *
       example_module__blinker_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExampleModule__BlinkerStatus *)
     protobuf_c_message_unpack (&example_module__blinker_status__descriptor,
                                allocator, len, data);
}
void   example_module__blinker_status__free_unpacked
                     (ExampleModule__BlinkerStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &example_module__blinker_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   example_module__lights_status__init
                     (ExampleModule__LightsStatus         *message)
{
  static const ExampleModule__LightsStatus init_value = EXAMPLE_MODULE__LIGHTS_STATUS__INIT;
  *message = init_value;
}
size_t example_module__lights_status__get_packed_size
                     (const ExampleModule__LightsStatus *message)
{
  assert(message->base.descriptor == &example_module__lights_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t example_module__lights_status__pack
                     (const ExampleModule__LightsStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &example_module__lights_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t example_module__lights_status__pack_to_buffer
                     (const ExampleModule__LightsStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &example_module__lights_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExampleModule__LightsStatus *
       example_module__lights_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExampleModule__LightsStatus *)
     protobuf_c_message_unpack (&example_module__lights_status__descriptor,
                                allocator, len, data);
}
void   example_module__lights_status__free_unpacked
                     (ExampleModule__LightsStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &example_module__lights_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   example_module__blinker_command__init
                     (ExampleModule__BlinkerCommand         *message)
{
  static const ExampleModule__BlinkerCommand init_value = EXAMPLE_MODULE__BLINKER_COMMAND__INIT;
  *message = init_value;
}
size_t example_module__blinker_command__get_packed_size
                     (const ExampleModule__BlinkerCommand *message)
{
  assert(message->base.descriptor == &example_module__blinker_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t example_module__blinker_command__pack
                     (const ExampleModule__BlinkerCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &example_module__blinker_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t example_module__blinker_command__pack_to_buffer
                     (const ExampleModule__BlinkerCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &example_module__blinker_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExampleModule__BlinkerCommand *
       example_module__blinker_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExampleModule__BlinkerCommand *)
     protobuf_c_message_unpack (&example_module__blinker_command__descriptor,
                                allocator, len, data);
}
void   example_module__blinker_command__free_unpacked
                     (ExampleModule__BlinkerCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &example_module__blinker_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   example_module__lights_command__init
                     (ExampleModule__LightsCommand         *message)
{
  static const ExampleModule__LightsCommand init_value = EXAMPLE_MODULE__LIGHTS_COMMAND__INIT;
  *message = init_value;
}
size_t example_module__lights_command__get_packed_size
                     (const ExampleModule__LightsCommand *message)
{
  assert(message->base.descriptor == &example_module__lights_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t example_module__lights_command__pack
                     (const ExampleModule__LightsCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &example_module__lights_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t example_module__lights_command__pack_to_buffer
                     (const ExampleModule__LightsCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &example_module__lights_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExampleModule__LightsCommand *
       example_module__lights_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExampleModule__LightsCommand *)
     protobuf_c_message_unpack (&example_module__lights_command__descriptor,
                                allocator, len, data);
}
void   example_module__lights_command__free_unpacked
                     (ExampleModule__LightsCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &example_module__lights_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   example_module__blinker_error__init
                     (ExampleModule__BlinkerError         *message)
{
  static const ExampleModule__BlinkerError init_value = EXAMPLE_MODULE__BLINKER_ERROR__INIT;
  *message = init_value;
}
size_t example_module__blinker_error__get_packed_size
                     (const ExampleModule__BlinkerError *message)
{
  assert(message->base.descriptor == &example_module__blinker_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t example_module__blinker_error__pack
                     (const ExampleModule__BlinkerError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &example_module__blinker_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t example_module__blinker_error__pack_to_buffer
                     (const ExampleModule__BlinkerError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &example_module__blinker_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExampleModule__BlinkerError *
       example_module__blinker_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExampleModule__BlinkerError *)
     protobuf_c_message_unpack (&example_module__blinker_error__descriptor,
                                allocator, len, data);
}
void   example_module__blinker_error__free_unpacked
                     (ExampleModule__BlinkerError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &example_module__blinker_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   example_module__lights_error__init
                     (ExampleModule__LightsError         *message)
{
  static const ExampleModule__LightsError init_value = EXAMPLE_MODULE__LIGHTS_ERROR__INIT;
  *message = init_value;
}
size_t example_module__lights_error__get_packed_size
                     (const ExampleModule__LightsError *message)
{
  assert(message->base.descriptor == &example_module__lights_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t example_module__lights_error__pack
                     (const ExampleModule__LightsError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &example_module__lights_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t example_module__lights_error__pack_to_buffer
                     (const ExampleModule__LightsError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &example_module__lights_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExampleModule__LightsError *
       example_module__lights_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExampleModule__LightsError *)
     protobuf_c_message_unpack (&example_module__lights_error__descriptor,
                                allocator, len, data);
}
void   example_module__lights_error__free_unpacked
                     (ExampleModule__LightsError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &example_module__lights_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor example_module__blinker_status__field_descriptors[1] =
{
  {
    "isFlashing",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ExampleModule__BlinkerStatus, isflashing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned example_module__blinker_status__field_indices_by_name[] = {
  0,   /* field[0] = isFlashing */
};
static const ProtobufCIntRange example_module__blinker_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor example_module__blinker_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExampleModule.BlinkerStatus",
  "BlinkerStatus",
  "ExampleModule__BlinkerStatus",
  "ExampleModule",
  sizeof(ExampleModule__BlinkerStatus),
  1,
  example_module__blinker_status__field_descriptors,
  example_module__blinker_status__field_indices_by_name,
  1,  example_module__blinker_status__number_ranges,
  (ProtobufCMessageInit) example_module__blinker_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor example_module__lights_status__field_descriptors[1] =
{
  {
    "isOn",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ExampleModule__LightsStatus, ison),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned example_module__lights_status__field_indices_by_name[] = {
  0,   /* field[0] = isOn */
};
static const ProtobufCIntRange example_module__lights_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor example_module__lights_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExampleModule.LightsStatus",
  "LightsStatus",
  "ExampleModule__LightsStatus",
  "ExampleModule",
  sizeof(ExampleModule__LightsStatus),
  1,
  example_module__lights_status__field_descriptors,
  example_module__lights_status__field_indices_by_name,
  1,  example_module__lights_status__number_ranges,
  (ProtobufCMessageInit) example_module__lights_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue example_module__blinker_command__command__enum_values_by_number[2] =
{
  { "TURN_ON", "EXAMPLE_MODULE__BLINKER_COMMAND__COMMAND__TURN_ON", 0 },
  { "TURN_OFF", "EXAMPLE_MODULE__BLINKER_COMMAND__COMMAND__TURN_OFF", 1 },
};
static const ProtobufCIntRange example_module__blinker_command__command__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex example_module__blinker_command__command__enum_values_by_name[2] =
{
  { "TURN_OFF", 1 },
  { "TURN_ON", 0 },
};
const ProtobufCEnumDescriptor example_module__blinker_command__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ExampleModule.BlinkerCommand.Command",
  "Command",
  "ExampleModule__BlinkerCommand__Command",
  "ExampleModule",
  2,
  example_module__blinker_command__command__enum_values_by_number,
  2,
  example_module__blinker_command__command__enum_values_by_name,
  1,
  example_module__blinker_command__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor example_module__blinker_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ExampleModule__BlinkerCommand, command),
    &example_module__blinker_command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned example_module__blinker_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange example_module__blinker_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor example_module__blinker_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExampleModule.BlinkerCommand",
  "BlinkerCommand",
  "ExampleModule__BlinkerCommand",
  "ExampleModule",
  sizeof(ExampleModule__BlinkerCommand),
  1,
  example_module__blinker_command__field_descriptors,
  example_module__blinker_command__field_indices_by_name,
  1,  example_module__blinker_command__number_ranges,
  (ProtobufCMessageInit) example_module__blinker_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue example_module__lights_command__command__enum_values_by_number[1] =
{
  { "PRESS", "EXAMPLE_MODULE__LIGHTS_COMMAND__COMMAND__PRESS", 0 },
};
static const ProtobufCIntRange example_module__lights_command__command__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex example_module__lights_command__command__enum_values_by_name[1] =
{
  { "PRESS", 0 },
};
const ProtobufCEnumDescriptor example_module__lights_command__command__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ExampleModule.LightsCommand.Command",
  "Command",
  "ExampleModule__LightsCommand__Command",
  "ExampleModule",
  1,
  example_module__lights_command__command__enum_values_by_number,
  1,
  example_module__lights_command__command__enum_values_by_name,
  1,
  example_module__lights_command__command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor example_module__lights_command__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ExampleModule__LightsCommand, command),
    &example_module__lights_command__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned example_module__lights_command__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange example_module__lights_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor example_module__lights_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExampleModule.LightsCommand",
  "LightsCommand",
  "ExampleModule__LightsCommand",
  "ExampleModule",
  sizeof(ExampleModule__LightsCommand),
  1,
  example_module__lights_command__field_descriptors,
  example_module__lights_command__field_indices_by_name,
  1,  example_module__lights_command__number_ranges,
  (ProtobufCMessageInit) example_module__lights_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor example_module__blinker_error__field_descriptors[1] =
{
  {
    "errorMessage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExampleModule__BlinkerError, errormessage),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned example_module__blinker_error__field_indices_by_name[] = {
  0,   /* field[0] = errorMessage */
};
static const ProtobufCIntRange example_module__blinker_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor example_module__blinker_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExampleModule.BlinkerError",
  "BlinkerError",
  "ExampleModule__BlinkerError",
  "ExampleModule",
  sizeof(ExampleModule__BlinkerError),
  1,
  example_module__blinker_error__field_descriptors,
  example_module__blinker_error__field_indices_by_name,
  1,  example_module__blinker_error__number_ranges,
  (ProtobufCMessageInit) example_module__blinker_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor example_module__lights_error__field_descriptors[1] =
{
  {
    "errorMessage",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExampleModule__LightsError, errormessage),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned example_module__lights_error__field_indices_by_name[] = {
  0,   /* field[0] = errorMessage */
};
static const ProtobufCIntRange example_module__lights_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor example_module__lights_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExampleModule.LightsError",
  "LightsError",
  "ExampleModule__LightsError",
  "ExampleModule",
  sizeof(ExampleModule__LightsError),
  1,
  example_module__lights_error__field_descriptors,
  example_module__lights_error__field_indices_by_name,
  1,  example_module__lights_error__number_ranges,
  (ProtobufCMessageInit) example_module__lights_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
