/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ExternalProtocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ExternalProtocol.pb-c.h"
void   external_protocol__external_server__init
                     (ExternalProtocol__ExternalServer         *message)
{
  static const ExternalProtocol__ExternalServer init_value = EXTERNAL_PROTOCOL__EXTERNAL_SERVER__INIT;
  *message = init_value;
}
size_t external_protocol__external_server__get_packed_size
                     (const ExternalProtocol__ExternalServer *message)
{
  assert(message->base.descriptor == &external_protocol__external_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external_protocol__external_server__pack
                     (const ExternalProtocol__ExternalServer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external_protocol__external_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external_protocol__external_server__pack_to_buffer
                     (const ExternalProtocol__ExternalServer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external_protocol__external_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExternalProtocol__ExternalServer *
       external_protocol__external_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExternalProtocol__ExternalServer *)
     protobuf_c_message_unpack (&external_protocol__external_server__descriptor,
                                allocator, len, data);
}
void   external_protocol__external_server__free_unpacked
                     (ExternalProtocol__ExternalServer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &external_protocol__external_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   external_protocol__external_client__init
                     (ExternalProtocol__ExternalClient         *message)
{
  static const ExternalProtocol__ExternalClient init_value = EXTERNAL_PROTOCOL__EXTERNAL_CLIENT__INIT;
  *message = init_value;
}
size_t external_protocol__external_client__get_packed_size
                     (const ExternalProtocol__ExternalClient *message)
{
  assert(message->base.descriptor == &external_protocol__external_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external_protocol__external_client__pack
                     (const ExternalProtocol__ExternalClient *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external_protocol__external_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external_protocol__external_client__pack_to_buffer
                     (const ExternalProtocol__ExternalClient *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external_protocol__external_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExternalProtocol__ExternalClient *
       external_protocol__external_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExternalProtocol__ExternalClient *)
     protobuf_c_message_unpack (&external_protocol__external_client__descriptor,
                                allocator, len, data);
}
void   external_protocol__external_client__free_unpacked
                     (ExternalProtocol__ExternalClient *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &external_protocol__external_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   external_protocol__connect__init
                     (ExternalProtocol__Connect         *message)
{
  static const ExternalProtocol__Connect init_value = EXTERNAL_PROTOCOL__CONNECT__INIT;
  *message = init_value;
}
size_t external_protocol__connect__get_packed_size
                     (const ExternalProtocol__Connect *message)
{
  assert(message->base.descriptor == &external_protocol__connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external_protocol__connect__pack
                     (const ExternalProtocol__Connect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external_protocol__connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external_protocol__connect__pack_to_buffer
                     (const ExternalProtocol__Connect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external_protocol__connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExternalProtocol__Connect *
       external_protocol__connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExternalProtocol__Connect *)
     protobuf_c_message_unpack (&external_protocol__connect__descriptor,
                                allocator, len, data);
}
void   external_protocol__connect__free_unpacked
                     (ExternalProtocol__Connect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &external_protocol__connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   external_protocol__connect_response__init
                     (ExternalProtocol__ConnectResponse         *message)
{
  static const ExternalProtocol__ConnectResponse init_value = EXTERNAL_PROTOCOL__CONNECT_RESPONSE__INIT;
  *message = init_value;
}
size_t external_protocol__connect_response__get_packed_size
                     (const ExternalProtocol__ConnectResponse *message)
{
  assert(message->base.descriptor == &external_protocol__connect_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external_protocol__connect_response__pack
                     (const ExternalProtocol__ConnectResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external_protocol__connect_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external_protocol__connect_response__pack_to_buffer
                     (const ExternalProtocol__ConnectResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external_protocol__connect_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExternalProtocol__ConnectResponse *
       external_protocol__connect_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExternalProtocol__ConnectResponse *)
     protobuf_c_message_unpack (&external_protocol__connect_response__descriptor,
                                allocator, len, data);
}
void   external_protocol__connect_response__free_unpacked
                     (ExternalProtocol__ConnectResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &external_protocol__connect_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   external_protocol__status__init
                     (ExternalProtocol__Status         *message)
{
  static const ExternalProtocol__Status init_value = EXTERNAL_PROTOCOL__STATUS__INIT;
  *message = init_value;
}
size_t external_protocol__status__get_packed_size
                     (const ExternalProtocol__Status *message)
{
  assert(message->base.descriptor == &external_protocol__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external_protocol__status__pack
                     (const ExternalProtocol__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external_protocol__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external_protocol__status__pack_to_buffer
                     (const ExternalProtocol__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external_protocol__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExternalProtocol__Status *
       external_protocol__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExternalProtocol__Status *)
     protobuf_c_message_unpack (&external_protocol__status__descriptor,
                                allocator, len, data);
}
void   external_protocol__status__free_unpacked
                     (ExternalProtocol__Status *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &external_protocol__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   external_protocol__status_response__init
                     (ExternalProtocol__StatusResponse         *message)
{
  static const ExternalProtocol__StatusResponse init_value = EXTERNAL_PROTOCOL__STATUS_RESPONSE__INIT;
  *message = init_value;
}
size_t external_protocol__status_response__get_packed_size
                     (const ExternalProtocol__StatusResponse *message)
{
  assert(message->base.descriptor == &external_protocol__status_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external_protocol__status_response__pack
                     (const ExternalProtocol__StatusResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external_protocol__status_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external_protocol__status_response__pack_to_buffer
                     (const ExternalProtocol__StatusResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external_protocol__status_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExternalProtocol__StatusResponse *
       external_protocol__status_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExternalProtocol__StatusResponse *)
     protobuf_c_message_unpack (&external_protocol__status_response__descriptor,
                                allocator, len, data);
}
void   external_protocol__status_response__free_unpacked
                     (ExternalProtocol__StatusResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &external_protocol__status_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   external_protocol__command__init
                     (ExternalProtocol__Command         *message)
{
  static const ExternalProtocol__Command init_value = EXTERNAL_PROTOCOL__COMMAND__INIT;
  *message = init_value;
}
size_t external_protocol__command__get_packed_size
                     (const ExternalProtocol__Command *message)
{
  assert(message->base.descriptor == &external_protocol__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external_protocol__command__pack
                     (const ExternalProtocol__Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external_protocol__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external_protocol__command__pack_to_buffer
                     (const ExternalProtocol__Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external_protocol__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExternalProtocol__Command *
       external_protocol__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExternalProtocol__Command *)
     protobuf_c_message_unpack (&external_protocol__command__descriptor,
                                allocator, len, data);
}
void   external_protocol__command__free_unpacked
                     (ExternalProtocol__Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &external_protocol__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   external_protocol__command_response__init
                     (ExternalProtocol__CommandResponse         *message)
{
  static const ExternalProtocol__CommandResponse init_value = EXTERNAL_PROTOCOL__COMMAND_RESPONSE__INIT;
  *message = init_value;
}
size_t external_protocol__command_response__get_packed_size
                     (const ExternalProtocol__CommandResponse *message)
{
  assert(message->base.descriptor == &external_protocol__command_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t external_protocol__command_response__pack
                     (const ExternalProtocol__CommandResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &external_protocol__command_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t external_protocol__command_response__pack_to_buffer
                     (const ExternalProtocol__CommandResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &external_protocol__command_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExternalProtocol__CommandResponse *
       external_protocol__command_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExternalProtocol__CommandResponse *)
     protobuf_c_message_unpack (&external_protocol__command_response__descriptor,
                                allocator, len, data);
}
void   external_protocol__command_response__free_unpacked
                     (ExternalProtocol__CommandResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &external_protocol__command_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor external_protocol__external_server__field_descriptors[3] =
{
  {
    "connectResponse",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ExternalProtocol__ExternalServer, message_type_case),
    offsetof(ExternalProtocol__ExternalServer, connectresponse),
    &external_protocol__connect_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statusResponse",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ExternalProtocol__ExternalServer, message_type_case),
    offsetof(ExternalProtocol__ExternalServer, statusresponse),
    &external_protocol__status_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ExternalProtocol__ExternalServer, message_type_case),
    offsetof(ExternalProtocol__ExternalServer, command),
    &external_protocol__command__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external_protocol__external_server__field_indices_by_name[] = {
  2,   /* field[2] = command */
  0,   /* field[0] = connectResponse */
  1,   /* field[1] = statusResponse */
};
static const ProtobufCIntRange external_protocol__external_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor external_protocol__external_server__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExternalProtocol.ExternalServer",
  "ExternalServer",
  "ExternalProtocol__ExternalServer",
  "ExternalProtocol",
  sizeof(ExternalProtocol__ExternalServer),
  3,
  external_protocol__external_server__field_descriptors,
  external_protocol__external_server__field_indices_by_name,
  1,  external_protocol__external_server__number_ranges,
  (ProtobufCMessageInit) external_protocol__external_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor external_protocol__external_client__field_descriptors[3] =
{
  {
    "connect",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ExternalProtocol__ExternalClient, message_type_case),
    offsetof(ExternalProtocol__ExternalClient, connect),
    &external_protocol__connect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ExternalProtocol__ExternalClient, message_type_case),
    offsetof(ExternalProtocol__ExternalClient, status),
    &external_protocol__status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commandResponse",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ExternalProtocol__ExternalClient, message_type_case),
    offsetof(ExternalProtocol__ExternalClient, commandresponse),
    &external_protocol__command_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external_protocol__external_client__field_indices_by_name[] = {
  2,   /* field[2] = commandResponse */
  0,   /* field[0] = connect */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange external_protocol__external_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor external_protocol__external_client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExternalProtocol.ExternalClient",
  "ExternalClient",
  "ExternalProtocol__ExternalClient",
  "ExternalProtocol",
  sizeof(ExternalProtocol__ExternalClient),
  3,
  external_protocol__external_client__field_descriptors,
  external_protocol__external_client__field_indices_by_name,
  1,  external_protocol__external_client__number_ranges,
  (ProtobufCMessageInit) external_protocol__external_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor external_protocol__connect__field_descriptors[4] =
{
  {
    "sessionId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Connect, sessionid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "company",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Connect, company),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicleName",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Connect, vehiclename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "devices",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ExternalProtocol__Connect, n_devices),
    offsetof(ExternalProtocol__Connect, devices),
    &internal_protocol__device__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external_protocol__connect__field_indices_by_name[] = {
  1,   /* field[1] = company */
  3,   /* field[3] = devices */
  0,   /* field[0] = sessionId */
  2,   /* field[2] = vehicleName */
};
static const ProtobufCIntRange external_protocol__connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor external_protocol__connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExternalProtocol.Connect",
  "Connect",
  "ExternalProtocol__Connect",
  "ExternalProtocol",
  sizeof(ExternalProtocol__Connect),
  4,
  external_protocol__connect__field_descriptors,
  external_protocol__connect__field_indices_by_name,
  1,  external_protocol__connect__number_ranges,
  (ProtobufCMessageInit) external_protocol__connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue external_protocol__connect_response__type__enum_values_by_number[2] =
{
  { "OK", "EXTERNAL_PROTOCOL__CONNECT_RESPONSE__TYPE__OK", 0 },
  { "ALREADY_LOGGED", "EXTERNAL_PROTOCOL__CONNECT_RESPONSE__TYPE__ALREADY_LOGGED", 1 },
};
static const ProtobufCIntRange external_protocol__connect_response__type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex external_protocol__connect_response__type__enum_values_by_name[2] =
{
  { "ALREADY_LOGGED", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor external_protocol__connect_response__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ExternalProtocol.ConnectResponse.Type",
  "Type",
  "ExternalProtocol__ConnectResponse__Type",
  "ExternalProtocol",
  2,
  external_protocol__connect_response__type__enum_values_by_number,
  2,
  external_protocol__connect_response__type__enum_values_by_name,
  1,
  external_protocol__connect_response__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor external_protocol__connect_response__field_descriptors[2] =
{
  {
    "sessionId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__ConnectResponse, sessionid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__ConnectResponse, type),
    &external_protocol__connect_response__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external_protocol__connect_response__field_indices_by_name[] = {
  0,   /* field[0] = sessionId */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange external_protocol__connect_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor external_protocol__connect_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExternalProtocol.ConnectResponse",
  "ConnectResponse",
  "ExternalProtocol__ConnectResponse",
  "ExternalProtocol",
  sizeof(ExternalProtocol__ConnectResponse),
  2,
  external_protocol__connect_response__field_descriptors,
  external_protocol__connect_response__field_indices_by_name,
  1,  external_protocol__connect_response__number_ranges,
  (ProtobufCMessageInit) external_protocol__connect_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue external_protocol__status__device_state__enum_values_by_number[4] =
{
  { "CONNECTING", "EXTERNAL_PROTOCOL__STATUS__DEVICE_STATE__CONNECTING", 0 },
  { "RUNNING", "EXTERNAL_PROTOCOL__STATUS__DEVICE_STATE__RUNNING", 1 },
  { "ERROR", "EXTERNAL_PROTOCOL__STATUS__DEVICE_STATE__ERROR", 2 },
  { "DISCONNECT", "EXTERNAL_PROTOCOL__STATUS__DEVICE_STATE__DISCONNECT", 3 },
};
static const ProtobufCIntRange external_protocol__status__device_state__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex external_protocol__status__device_state__enum_values_by_name[4] =
{
  { "CONNECTING", 0 },
  { "DISCONNECT", 3 },
  { "ERROR", 2 },
  { "RUNNING", 1 },
};
const ProtobufCEnumDescriptor external_protocol__status__device_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ExternalProtocol.Status.DeviceState",
  "DeviceState",
  "ExternalProtocol__Status__DeviceState",
  "ExternalProtocol",
  4,
  external_protocol__status__device_state__enum_values_by_number,
  4,
  external_protocol__status__device_state__enum_values_by_name,
  1,
  external_protocol__status__device_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor external_protocol__status__field_descriptors[5] =
{
  {
    "sessionId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Status, sessionid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceState",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Status, devicestate),
    &external_protocol__status__device_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageCounter",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Status, messagecounter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceStatus",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Status, devicestatus),
    &internal_protocol__device_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorMessage",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Status, errormessage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external_protocol__status__field_indices_by_name[] = {
  1,   /* field[1] = deviceState */
  3,   /* field[3] = deviceStatus */
  4,   /* field[4] = errorMessage */
  2,   /* field[2] = messageCounter */
  0,   /* field[0] = sessionId */
};
static const ProtobufCIntRange external_protocol__status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor external_protocol__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExternalProtocol.Status",
  "Status",
  "ExternalProtocol__Status",
  "ExternalProtocol",
  sizeof(ExternalProtocol__Status),
  5,
  external_protocol__status__field_descriptors,
  external_protocol__status__field_indices_by_name,
  1,  external_protocol__status__number_ranges,
  (ProtobufCMessageInit) external_protocol__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue external_protocol__status_response__type__enum_values_by_number[1] =
{
  { "OK", "EXTERNAL_PROTOCOL__STATUS_RESPONSE__TYPE__OK", 0 },
};
static const ProtobufCIntRange external_protocol__status_response__type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex external_protocol__status_response__type__enum_values_by_name[1] =
{
  { "OK", 0 },
};
const ProtobufCEnumDescriptor external_protocol__status_response__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ExternalProtocol.StatusResponse.Type",
  "Type",
  "ExternalProtocol__StatusResponse__Type",
  "ExternalProtocol",
  1,
  external_protocol__status_response__type__enum_values_by_number,
  1,
  external_protocol__status_response__type__enum_values_by_name,
  1,
  external_protocol__status_response__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor external_protocol__status_response__field_descriptors[3] =
{
  {
    "sessionId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__StatusResponse, sessionid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__StatusResponse, type),
    &external_protocol__status_response__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageCounter",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__StatusResponse, messagecounter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external_protocol__status_response__field_indices_by_name[] = {
  2,   /* field[2] = messageCounter */
  0,   /* field[0] = sessionId */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange external_protocol__status_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor external_protocol__status_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExternalProtocol.StatusResponse",
  "StatusResponse",
  "ExternalProtocol__StatusResponse",
  "ExternalProtocol",
  sizeof(ExternalProtocol__StatusResponse),
  3,
  external_protocol__status_response__field_descriptors,
  external_protocol__status_response__field_indices_by_name,
  1,  external_protocol__status_response__number_ranges,
  (ProtobufCMessageInit) external_protocol__status_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor external_protocol__command__field_descriptors[3] =
{
  {
    "sessionId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Command, sessionid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageCounter",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Command, messagecounter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceCommand",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__Command, devicecommand),
    &internal_protocol__device_command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external_protocol__command__field_indices_by_name[] = {
  2,   /* field[2] = deviceCommand */
  1,   /* field[1] = messageCounter */
  0,   /* field[0] = sessionId */
};
static const ProtobufCIntRange external_protocol__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor external_protocol__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExternalProtocol.Command",
  "Command",
  "ExternalProtocol__Command",
  "ExternalProtocol",
  sizeof(ExternalProtocol__Command),
  3,
  external_protocol__command__field_descriptors,
  external_protocol__command__field_indices_by_name,
  1,  external_protocol__command__number_ranges,
  (ProtobufCMessageInit) external_protocol__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue external_protocol__command_response__type__enum_values_by_number[4] =
{
  { "OK", "EXTERNAL_PROTOCOL__COMMAND_RESPONSE__TYPE__OK", 0 },
  { "DEVICE_NOT_CONNECTED", "EXTERNAL_PROTOCOL__COMMAND_RESPONSE__TYPE__DEVICE_NOT_CONNECTED", 1 },
  { "DEVICE_NOT_SUPPORTED", "EXTERNAL_PROTOCOL__COMMAND_RESPONSE__TYPE__DEVICE_NOT_SUPPORTED", 2 },
  { "INVALID_COMMAND", "EXTERNAL_PROTOCOL__COMMAND_RESPONSE__TYPE__INVALID_COMMAND", 3 },
};
static const ProtobufCIntRange external_protocol__command_response__type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex external_protocol__command_response__type__enum_values_by_name[4] =
{
  { "DEVICE_NOT_CONNECTED", 1 },
  { "DEVICE_NOT_SUPPORTED", 2 },
  { "INVALID_COMMAND", 3 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor external_protocol__command_response__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ExternalProtocol.CommandResponse.Type",
  "Type",
  "ExternalProtocol__CommandResponse__Type",
  "ExternalProtocol",
  4,
  external_protocol__command_response__type__enum_values_by_number,
  4,
  external_protocol__command_response__type__enum_values_by_name,
  1,
  external_protocol__command_response__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor external_protocol__command_response__field_descriptors[3] =
{
  {
    "sessionId",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__CommandResponse, sessionid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__CommandResponse, type),
    &external_protocol__command_response__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageCounter",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ExternalProtocol__CommandResponse, messagecounter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned external_protocol__command_response__field_indices_by_name[] = {
  2,   /* field[2] = messageCounter */
  0,   /* field[0] = sessionId */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange external_protocol__command_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor external_protocol__command_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExternalProtocol.CommandResponse",
  "CommandResponse",
  "ExternalProtocol__CommandResponse",
  "ExternalProtocol",
  sizeof(ExternalProtocol__CommandResponse),
  3,
  external_protocol__command_response__field_descriptors,
  external_protocol__command_response__field_indices_by_name,
  1,  external_protocol__command_response__number_ranges,
  (ProtobufCMessageInit) external_protocol__command_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
