/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: InternalProtocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "InternalProtocol.pb-c.h"
void   internal_protocol__internal_client__init
                     (InternalProtocol__InternalClient         *message)
{
  static const InternalProtocol__InternalClient init_value = INTERNAL_PROTOCOL__INTERNAL_CLIENT__INIT;
  *message = init_value;
}
size_t internal_protocol__internal_client__get_packed_size
                     (const InternalProtocol__InternalClient *message)
{
  assert(message->base.descriptor == &internal_protocol__internal_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_protocol__internal_client__pack
                     (const InternalProtocol__InternalClient *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_protocol__internal_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_protocol__internal_client__pack_to_buffer
                     (const InternalProtocol__InternalClient *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_protocol__internal_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalProtocol__InternalClient *
       internal_protocol__internal_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalProtocol__InternalClient *)
     protobuf_c_message_unpack (&internal_protocol__internal_client__descriptor,
                                allocator, len, data);
}
void   internal_protocol__internal_client__free_unpacked
                     (InternalProtocol__InternalClient *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_protocol__internal_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   internal_protocol__internal_server__init
                     (InternalProtocol__InternalServer         *message)
{
  static const InternalProtocol__InternalServer init_value = INTERNAL_PROTOCOL__INTERNAL_SERVER__INIT;
  *message = init_value;
}
size_t internal_protocol__internal_server__get_packed_size
                     (const InternalProtocol__InternalServer *message)
{
  assert(message->base.descriptor == &internal_protocol__internal_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_protocol__internal_server__pack
                     (const InternalProtocol__InternalServer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_protocol__internal_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_protocol__internal_server__pack_to_buffer
                     (const InternalProtocol__InternalServer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_protocol__internal_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalProtocol__InternalServer *
       internal_protocol__internal_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalProtocol__InternalServer *)
     protobuf_c_message_unpack (&internal_protocol__internal_server__descriptor,
                                allocator, len, data);
}
void   internal_protocol__internal_server__free_unpacked
                     (InternalProtocol__InternalServer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_protocol__internal_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   internal_protocol__device_connect__init
                     (InternalProtocol__DeviceConnect         *message)
{
  static const InternalProtocol__DeviceConnect init_value = INTERNAL_PROTOCOL__DEVICE_CONNECT__INIT;
  *message = init_value;
}
size_t internal_protocol__device_connect__get_packed_size
                     (const InternalProtocol__DeviceConnect *message)
{
  assert(message->base.descriptor == &internal_protocol__device_connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_protocol__device_connect__pack
                     (const InternalProtocol__DeviceConnect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_protocol__device_connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_protocol__device_connect__pack_to_buffer
                     (const InternalProtocol__DeviceConnect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_protocol__device_connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalProtocol__DeviceConnect *
       internal_protocol__device_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalProtocol__DeviceConnect *)
     protobuf_c_message_unpack (&internal_protocol__device_connect__descriptor,
                                allocator, len, data);
}
void   internal_protocol__device_connect__free_unpacked
                     (InternalProtocol__DeviceConnect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_protocol__device_connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   internal_protocol__device_connect_response__init
                     (InternalProtocol__DeviceConnectResponse         *message)
{
  static const InternalProtocol__DeviceConnectResponse init_value = INTERNAL_PROTOCOL__DEVICE_CONNECT_RESPONSE__INIT;
  *message = init_value;
}
size_t internal_protocol__device_connect_response__get_packed_size
                     (const InternalProtocol__DeviceConnectResponse *message)
{
  assert(message->base.descriptor == &internal_protocol__device_connect_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_protocol__device_connect_response__pack
                     (const InternalProtocol__DeviceConnectResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_protocol__device_connect_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_protocol__device_connect_response__pack_to_buffer
                     (const InternalProtocol__DeviceConnectResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_protocol__device_connect_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalProtocol__DeviceConnectResponse *
       internal_protocol__device_connect_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalProtocol__DeviceConnectResponse *)
     protobuf_c_message_unpack (&internal_protocol__device_connect_response__descriptor,
                                allocator, len, data);
}
void   internal_protocol__device_connect_response__free_unpacked
                     (InternalProtocol__DeviceConnectResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_protocol__device_connect_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   internal_protocol__device_status__init
                     (InternalProtocol__DeviceStatus         *message)
{
  static const InternalProtocol__DeviceStatus init_value = INTERNAL_PROTOCOL__DEVICE_STATUS__INIT;
  *message = init_value;
}
size_t internal_protocol__device_status__get_packed_size
                     (const InternalProtocol__DeviceStatus *message)
{
  assert(message->base.descriptor == &internal_protocol__device_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_protocol__device_status__pack
                     (const InternalProtocol__DeviceStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_protocol__device_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_protocol__device_status__pack_to_buffer
                     (const InternalProtocol__DeviceStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_protocol__device_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalProtocol__DeviceStatus *
       internal_protocol__device_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalProtocol__DeviceStatus *)
     protobuf_c_message_unpack (&internal_protocol__device_status__descriptor,
                                allocator, len, data);
}
void   internal_protocol__device_status__free_unpacked
                     (InternalProtocol__DeviceStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_protocol__device_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   internal_protocol__device_command__init
                     (InternalProtocol__DeviceCommand         *message)
{
  static const InternalProtocol__DeviceCommand init_value = INTERNAL_PROTOCOL__DEVICE_COMMAND__INIT;
  *message = init_value;
}
size_t internal_protocol__device_command__get_packed_size
                     (const InternalProtocol__DeviceCommand *message)
{
  assert(message->base.descriptor == &internal_protocol__device_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_protocol__device_command__pack
                     (const InternalProtocol__DeviceCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_protocol__device_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_protocol__device_command__pack_to_buffer
                     (const InternalProtocol__DeviceCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_protocol__device_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalProtocol__DeviceCommand *
       internal_protocol__device_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalProtocol__DeviceCommand *)
     protobuf_c_message_unpack (&internal_protocol__device_command__descriptor,
                                allocator, len, data);
}
void   internal_protocol__device_command__free_unpacked
                     (InternalProtocol__DeviceCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_protocol__device_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   internal_protocol__device__init
                     (InternalProtocol__Device         *message)
{
  static const InternalProtocol__Device init_value = INTERNAL_PROTOCOL__DEVICE__INIT;
  *message = init_value;
}
size_t internal_protocol__device__get_packed_size
                     (const InternalProtocol__Device *message)
{
  assert(message->base.descriptor == &internal_protocol__device__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t internal_protocol__device__pack
                     (const InternalProtocol__Device *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &internal_protocol__device__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t internal_protocol__device__pack_to_buffer
                     (const InternalProtocol__Device *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &internal_protocol__device__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InternalProtocol__Device *
       internal_protocol__device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InternalProtocol__Device *)
     protobuf_c_message_unpack (&internal_protocol__device__descriptor,
                                allocator, len, data);
}
void   internal_protocol__device__free_unpacked
                     (InternalProtocol__Device *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &internal_protocol__device__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor internal_protocol__internal_client__field_descriptors[2] =
{
  {
    "deviceConnect",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(InternalProtocol__InternalClient, message_type_case),
    offsetof(InternalProtocol__InternalClient, deviceconnect),
    &internal_protocol__device_connect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceStatus",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(InternalProtocol__InternalClient, message_type_case),
    offsetof(InternalProtocol__InternalClient, devicestatus),
    &internal_protocol__device_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_protocol__internal_client__field_indices_by_name[] = {
  0,   /* field[0] = deviceConnect */
  1,   /* field[1] = deviceStatus */
};
static const ProtobufCIntRange internal_protocol__internal_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor internal_protocol__internal_client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalProtocol.InternalClient",
  "InternalClient",
  "InternalProtocol__InternalClient",
  "InternalProtocol",
  sizeof(InternalProtocol__InternalClient),
  2,
  internal_protocol__internal_client__field_descriptors,
  internal_protocol__internal_client__field_indices_by_name,
  1,  internal_protocol__internal_client__number_ranges,
  (ProtobufCMessageInit) internal_protocol__internal_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor internal_protocol__internal_server__field_descriptors[2] =
{
  {
    "deviceConnectResponse",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(InternalProtocol__InternalServer, message_type_case),
    offsetof(InternalProtocol__InternalServer, deviceconnectresponse),
    &internal_protocol__device_connect_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceCommand",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(InternalProtocol__InternalServer, message_type_case),
    offsetof(InternalProtocol__InternalServer, devicecommand),
    &internal_protocol__device_command__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_protocol__internal_server__field_indices_by_name[] = {
  1,   /* field[1] = deviceCommand */
  0,   /* field[0] = deviceConnectResponse */
};
static const ProtobufCIntRange internal_protocol__internal_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor internal_protocol__internal_server__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalProtocol.InternalServer",
  "InternalServer",
  "InternalProtocol__InternalServer",
  "InternalProtocol",
  sizeof(InternalProtocol__InternalServer),
  2,
  internal_protocol__internal_server__field_descriptors,
  internal_protocol__internal_server__field_indices_by_name,
  1,  internal_protocol__internal_server__number_ranges,
  (ProtobufCMessageInit) internal_protocol__internal_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor internal_protocol__device_connect__field_descriptors[1] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__DeviceConnect, device),
    &internal_protocol__device__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_protocol__device_connect__field_indices_by_name[] = {
  0,   /* field[0] = device */
};
static const ProtobufCIntRange internal_protocol__device_connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor internal_protocol__device_connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalProtocol.DeviceConnect",
  "DeviceConnect",
  "InternalProtocol__DeviceConnect",
  "InternalProtocol",
  sizeof(InternalProtocol__DeviceConnect),
  1,
  internal_protocol__device_connect__field_descriptors,
  internal_protocol__device_connect__field_indices_by_name,
  1,  internal_protocol__device_connect__number_ranges,
  (ProtobufCMessageInit) internal_protocol__device_connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue internal_protocol__device_connect_response__response_type__enum_values_by_number[5] =
{
  { "OK", "INTERNAL_PROTOCOL__DEVICE_CONNECT_RESPONSE__RESPONSE_TYPE__OK", 0 },
  { "ALREADY_CONNECTED", "INTERNAL_PROTOCOL__DEVICE_CONNECT_RESPONSE__RESPONSE_TYPE__ALREADY_CONNECTED", 1 },
  { "MODULE_NOT_SUPPORTED", "INTERNAL_PROTOCOL__DEVICE_CONNECT_RESPONSE__RESPONSE_TYPE__MODULE_NOT_SUPPORTED", 2 },
  { "DEVICE_NOT_SUPPORTED", "INTERNAL_PROTOCOL__DEVICE_CONNECT_RESPONSE__RESPONSE_TYPE__DEVICE_NOT_SUPPORTED", 3 },
  { "HIGHER_PRIORITY_ALREADY_CONNECTED", "INTERNAL_PROTOCOL__DEVICE_CONNECT_RESPONSE__RESPONSE_TYPE__HIGHER_PRIORITY_ALREADY_CONNECTED", 4 },
};
static const ProtobufCIntRange internal_protocol__device_connect_response__response_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex internal_protocol__device_connect_response__response_type__enum_values_by_name[5] =
{
  { "ALREADY_CONNECTED", 1 },
  { "DEVICE_NOT_SUPPORTED", 3 },
  { "HIGHER_PRIORITY_ALREADY_CONNECTED", 4 },
  { "MODULE_NOT_SUPPORTED", 2 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor internal_protocol__device_connect_response__response_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "InternalProtocol.DeviceConnectResponse.ResponseType",
  "ResponseType",
  "InternalProtocol__DeviceConnectResponse__ResponseType",
  "InternalProtocol",
  5,
  internal_protocol__device_connect_response__response_type__enum_values_by_number,
  5,
  internal_protocol__device_connect_response__response_type__enum_values_by_name,
  1,
  internal_protocol__device_connect_response__response_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor internal_protocol__device_connect_response__field_descriptors[2] =
{
  {
    "responseType",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__DeviceConnectResponse, responsetype),
    &internal_protocol__device_connect_response__response_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__DeviceConnectResponse, device),
    &internal_protocol__device__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_protocol__device_connect_response__field_indices_by_name[] = {
  1,   /* field[1] = device */
  0,   /* field[0] = responseType */
};
static const ProtobufCIntRange internal_protocol__device_connect_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor internal_protocol__device_connect_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalProtocol.DeviceConnectResponse",
  "DeviceConnectResponse",
  "InternalProtocol__DeviceConnectResponse",
  "InternalProtocol",
  sizeof(InternalProtocol__DeviceConnectResponse),
  2,
  internal_protocol__device_connect_response__field_descriptors,
  internal_protocol__device_connect_response__field_indices_by_name,
  1,  internal_protocol__device_connect_response__number_ranges,
  (ProtobufCMessageInit) internal_protocol__device_connect_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor internal_protocol__device_status__field_descriptors[2] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__DeviceStatus, device),
    &internal_protocol__device__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statusData",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__DeviceStatus, statusdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_protocol__device_status__field_indices_by_name[] = {
  0,   /* field[0] = device */
  1,   /* field[1] = statusData */
};
static const ProtobufCIntRange internal_protocol__device_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor internal_protocol__device_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalProtocol.DeviceStatus",
  "DeviceStatus",
  "InternalProtocol__DeviceStatus",
  "InternalProtocol",
  sizeof(InternalProtocol__DeviceStatus),
  2,
  internal_protocol__device_status__field_descriptors,
  internal_protocol__device_status__field_indices_by_name,
  1,  internal_protocol__device_status__number_ranges,
  (ProtobufCMessageInit) internal_protocol__device_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor internal_protocol__device_command__field_descriptors[2] =
{
  {
    "device",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__DeviceCommand, device),
    &internal_protocol__device__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commandData",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__DeviceCommand, commanddata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_protocol__device_command__field_indices_by_name[] = {
  1,   /* field[1] = commandData */
  0,   /* field[0] = device */
};
static const ProtobufCIntRange internal_protocol__device_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor internal_protocol__device_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalProtocol.DeviceCommand",
  "DeviceCommand",
  "InternalProtocol__DeviceCommand",
  "InternalProtocol",
  sizeof(InternalProtocol__DeviceCommand),
  2,
  internal_protocol__device_command__field_descriptors,
  internal_protocol__device_command__field_indices_by_name,
  1,  internal_protocol__device_command__number_ranges,
  (ProtobufCMessageInit) internal_protocol__device_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue internal_protocol__device__module__enum_values_by_number[4] =
{
  { "RESERVED_MODULE", "INTERNAL_PROTOCOL__DEVICE__MODULE__RESERVED_MODULE", 0 },
  { "MISSION_MODULE", "INTERNAL_PROTOCOL__DEVICE__MODULE__MISSION_MODULE", 1 },
  { "CAR_ACCESSORY_MODULE", "INTERNAL_PROTOCOL__DEVICE__MODULE__CAR_ACCESSORY_MODULE", 2 },
  { "EXAMPLE_MODULE", "INTERNAL_PROTOCOL__DEVICE__MODULE__EXAMPLE_MODULE", 999 },
};
static const ProtobufCIntRange internal_protocol__device__module__value_ranges[] = {
{0, 0},{999, 3},{0, 4}
};
static const ProtobufCEnumValueIndex internal_protocol__device__module__enum_values_by_name[4] =
{
  { "CAR_ACCESSORY_MODULE", 2 },
  { "EXAMPLE_MODULE", 3 },
  { "MISSION_MODULE", 1 },
  { "RESERVED_MODULE", 0 },
};
const ProtobufCEnumDescriptor internal_protocol__device__module__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "InternalProtocol.Device.Module",
  "Module",
  "InternalProtocol__Device__Module",
  "InternalProtocol",
  4,
  internal_protocol__device__module__enum_values_by_number,
  4,
  internal_protocol__device__module__enum_values_by_name,
  2,
  internal_protocol__device__module__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor internal_protocol__device__field_descriptors[5] =
{
  {
    "module",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__Device, module),
    &internal_protocol__device__module__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceType",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__Device, devicetype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceRole",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__Device, devicerole),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceName",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__Device, devicename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "priority",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(InternalProtocol__Device, priority),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned internal_protocol__device__field_indices_by_name[] = {
  3,   /* field[3] = deviceName */
  2,   /* field[2] = deviceRole */
  1,   /* field[1] = deviceType */
  0,   /* field[0] = module */
  4,   /* field[4] = priority */
};
static const ProtobufCIntRange internal_protocol__device__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor internal_protocol__device__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InternalProtocol.Device",
  "Device",
  "InternalProtocol__Device",
  "InternalProtocol",
  sizeof(InternalProtocol__Device),
  5,
  internal_protocol__device__field_descriptors,
  internal_protocol__device__field_indices_by_name,
  1,  internal_protocol__device__number_ranges,
  (ProtobufCMessageInit) internal_protocol__device__init,
  NULL,NULL,NULL    /* reserved[123] */
};
